### PR TITLE
Change soft tabs

### PR DESCRIPTION
**Pull request by renancouto**
We are using this in `php` and `css` files, so I think it should be used here too

### CODE REVIEW

**Comment by janjaap** [comment]
👍

**Comment by tcboni** [comment]
why 4 T_T

**Comment by janjaap** [comment]
@tcboni Because we use that rule for other programming languages as well, mainly PHP. We should have one standard where that is concerned.

**Comment by janjaap** [comment]
👍 Merge away!

**Comment by renancouto** [comment]
Still needs to be done for the ES6 part 😞

**Pull request merged**
